##Copyright 2019 Pescaru Tudor Mihai

build:
	gcc pb1.c -o ninel
	gcc pb2.c -o vectsecv
	gcc pb3.c -o codeinvim
	gcc pb4.c -o nomogram
clean:
	rm -f ninel
	rm -f vectsecv
	rm -f codeinvim
	rm -f nomogram
